### ISSUE TITLE
First review

### ISSUE THREAD

**Issue by tomasesquivelgc** [hafiz1379/JS-capstone-project#22]
## This is the setup of our work
You can find the GitHub project (here)[https://github.com/hafiz1379/JS-capstone-project/projects/3]

There are **3** people in this group.

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good setup 👍🏿 



## Required Changes ♻️

- [ ] Please ensure all cards are assigned to team members, your cards don't have assignees yet. You should see a circle with the user's avatar on each card. See the example below:

 <img width="372" alt="assigned_card (4)" src="https://github.com/hafiz1379/JS-capstone-project/assets/69638013/60646750-b83c-43cc-b3a2-2021af6b7dda">
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tomasesquivelgc** [comment]
## Update
Issues are now assigned to every student.
